version: "3.8"


services:
  app:
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty


  db:
    restart: always
    image: postgres:15.1
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5434:5432"